name: AppStore Monitor

on:
  schedule:
    # 每小时运行一次
    - cron: '0 * * * *'
  workflow_dispatch:
    # 允许手动触发

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
      
    - name: 设置 Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: 运行监控脚本
      env:
        FANGTANG_KEY: ${{ secrets.FANGTANG_KEY }}
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          python appstore_monitor.py --force
        else
          python appstore_monitor.py
        fi 

    - name: Commit updated status file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add app_status.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Update app status [skip ci]"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }} 